backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"

collections:
  - name: "editoriales"
    label: "Editoriales"
    folder: "content/editoriales"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Cuerpo", name: "body", widget: "markdown"}

  - name: "paginas"
    label: "Pestañas Fijas"
    files:
      - file: "content/programacion.json"
        label: "Programación"
        name: "programacion"
        fields:
          - {label: "Título", name: "titulo", widget: "string"}
          - label: "Programas"
            name: "items"
            widget: "list"
            fields:
              - {label: "Nombre", name: "nombre", widget: "string"}
              - {label: "Hora", name: "detalle", widget: "string"}
